# Generated by Django 2.0 on 2021-09-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
