# Generated by Django 2.0 on 2021-09-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0006_auto_20210909_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_quantity',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='product',
            name='min_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
