# Generated by Django 3.2.7 on 2021-09-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0011_alter_shopcart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopcart',
        ),
    ]
