# Generated by Django 3.2.7 on 2021-09-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0013_shopcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopcart',
        ),
    ]
