# Generated by Django 3.2.7 on 2021-09-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizapp', '0021_paidorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paidorder',
            name='cart_code',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='paidorder',
            name='transac_code',
            field=models.CharField(max_length=10),
        ),
    ]
